apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-updated
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: redis:6.2
        ports:
        - containerPort: 8080
